### PR TITLE
Telegram receiving hotfix

### PR DESCRIPTION
**Pull request by koallann**
Fix for https://github.com/rapidpro/rapidpro/issues/1168.

### CODE REVIEW

**Comment by nicpottier** [comment]
Are you guys running this?

**Comment by koallann** [comment]
Not yet, we scheduled an update for today and then "unlock" the receiving in an our channel. The `pending_update_count` (https://core.telegram.org/bots/api#getwebhookinfo) for that channel is in more than 5k messages with a single Telegram user locking the channel receiving. I captured that user request and reproduced the receiving in my development env, file resolving (https://core.telegram.org/bots/api#getfile) is returning:
```json
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: wrong file_id or the file is temporarily unavailable"
}
```

**Comment by nicpottier** [comment]
Can you ship that and see if that resolves the queue you have? If so then we'll merge on our side.

**Comment by koallann** [comment]
Sure!

**Comment by koallann** [comment]
Hey @nicpottier, worked well for us 👍

**Pull request merged**
