### PR TITLE
Send msg in batches and add image msg type in the LINE channel

### PR DESCRIPTION
**Pull request by koallann**
This is a PR to increase the speed of receiving messages on LINE clients and support the image message type:

The LINE messaging API allows sending up to 5 messages at a time (https://developers.line.biz/en/reference/messaging-api/#send-push-message), so instead of sending each part of the message (from split by `maxMsgLength`) with its own request, this PR changes the behavior to send the message in these batches, increasing the speed of receiving messages on LINE clients.

### CODE REVIEW

**Comment by nicpottier** [comment]
Just to be clear, this affects the speed of sending, not receiving. It also will only make a difference for long or multipart messages. Are you guys running this?

**Comment by koallann** [comment]
Yeah, speed of sending from Courier and speed of receiving in LINE clients.

What was really requested by a customer was support for sending images and while I read the LINE docs I saw that it is possible to send batches of messages (up to 5) at a time, so I implemented that way to send the message text and the attachments at once.

**Comment by nicpottier** [comment]
Great, thanks. Will merge once the 5.4 freeze is over.

**Comment by matmsa27** [comment]
Hi @nicpottier , do you have any news about this PR?

**Comment by nicpottier** [comment]
Thanks for the reminder and the PR!

**Comment by matmsa27** [comment]
You are welcome @nicpottier , thank you.

**Pull request merged**
