### PR TITLE
fixing chatbase request body

### PR DESCRIPTION
**Pull request by periclesJ**
The chatbase API was updated due to this a few parameters of the request have changed causing erros trying to send data to the chatbase. This small adjustment solves this problem.

See here the current field values: https://chatbase.com/documentation/generic

### CODE REVIEW

**Comment by nicpottier** [comment]
Could you add a unit test for chatbase while you are at it?

**Comment by periclesJ** [comment]
I've added a unit test to evaluate the deprecated messageType.

**Comment by matmsa27** [comment]
Hi @nicpottier , do you have any news about this PR?

**Comment by nicpottier** [comment]
Apologies, internet problems over here last week. Looks good, thanks!

**Comment by matmsa27** [comment]
Hi @nicpottier , don't worry, no problems. Thanks a lot for your attention.

Regards. :)

**Pull request merged**
